/**
 * Skill indexing — the runtime half of file-backed skills (spec §5.1).
 *
 * Two sources of truth, one derived file:
 *
 *   skills/<name>/SKILL.md   presence = installed; frontmatter = name/description
 *   skills-state.json        exception list { "schema": 1, "disabled": [...] }
 *          │
 *          ▼  this indexer (workspace write/delete choke point, debounced)
 *   skills-registry.json     derived, runtime-owned, protection read_only
 *
 * The validation, limits, and registry shape are ported from the agent-space
 * `skill-loader` lambda so agents that already ran the loader are adopted
 * as-is rather than re-indexed into a different catalog.
 *
 * Authority does not move with the mechanics: this file reads and writes
 * ordinary VFS rows. It never executes skill text, authorizes files, enables
 * tools, or relaxes HIL. `requires` is not read here at all.
 *
 * Headless-safe: no Electron, no SQLite, no runtime imports — the host is a
 * structural interface that AdfWorkspace satisfies, so the pure logic below is
 * directly unit-testable.
 */

import type { FileProtectionLevel } from '@shared/types/adf-v02.types'
import { withSource } from '../runtime/execution-context'

export const SKILLS_ROOT = 'skills/'
export const SKILLS_REGISTRY_PATH = 'skills-registry.json'
export const SKILLS_STATE_PATH = 'skills-state.json'

/** Ported verbatim from the skill-loader lambda — see skills/skill-loader/SKILL.md. */
export const MAX_SKILL_FILE_BYTES = 256 * 1024
export const MAX_SKILLS = 48
export const MAX_REGISTRY_BYTES = 32 * 1024

/** Execution-context source for everything the indexer writes. */
export const SKILL_INDEX_SOURCE = 'system:skill_indexer'

/** Category and coalescing key for the mid-session catalog `loop_inject`. */
export const SKILLS_REGISTRY_INJECT_KEY = 'skills_registry'

/** Prefix of the injected payload — states that it replaces earlier catalogs. */
export const SKILLS_REGISTRY_INJECT_PREFIX = 'This catalog supersedes previous skill catalogs:'

const SKILL_NAME = /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/
const SKILL_FILE_PATH = /^skills\/[^/]+\/SKILL\.md$/

/** Marks the registry as derived so a reader never mistakes it for a source file. */
export const SKILLS_REGISTRY_NOTES =
  'Generated by the ADF runtime — edit skills/ and skills-state.json instead'

export interface SkillRegistryEntry {
  name: string
  /** Omitted for disabled skills: a bare name is rediscoverable at ~zero token cost. */
  description?: string
  path: string
  enabled: boolean
}

export interface SkillRegistry {
  schema: 1
  $notes: string
  skills: Record<string, SkillRegistryEntry>
  /**
   * Packages that exist on disk but are NOT in `skills`, each with the reason.
   * Omitted when there are none. Spec §5.1 requires rejections to be reported
   * rather than silently dropped, and the registry is the only artifact both
   * the model and the Studio panel already read.
   */
  rejected?: RejectedSkill[]
}

export interface RejectedSkill {
  path: string
  reason: string
}

/**
 * Bounds on the rejected list as PERSISTED. The full list still reaches
 * callers via SkillIndexResult.rejected; these caps only stop a directory full
 * of malformed packages from crowding the real catalog out of the 32 KB budget.
 */
export const MAX_REGISTRY_REJECTED = 32
const MAX_REJECTED_REASON_CHARS = 200
const MAX_REJECTED_PATH_CHARS = 200

/** One candidate `skills/<name>/SKILL.md` row as the indexer sees it. */
export interface SkillSource {
  path: string
  size: number
  /** null when the row disappeared between listing and reading. */
  content: string | null
}

export interface SkillIndexResult {
  registry: SkillRegistry
  /** Exactly the bytes written to `skills-registry.json` (pretty JSON + trailing newline). */
  json: string
  rejected: RejectedSkill[]
  skillCount: number
}

/** True for the paths whose writes/deletes must trigger a reindex. */
export function isSkillIndexPath(path: string): boolean {
  return path === SKILLS_STATE_PATH || SKILL_FILE_PATH.test(path)
}

/** True for a listed VFS row that is a skill package manifest. */
export function isSkillManifestPath(path: string): boolean {
  return SKILL_FILE_PATH.test(path)
}

export interface SkillsState {
  disabled: string[]
  /**
   * Why the file could not be read, when it exists but does not parse. Fail-open
   * is deliberate — a typo in the mute list must never blank the catalog — but
   * the agent has to be TOLD, or its mutes silently stop applying.
   */
  error?: string
}

/**
 * Read skills-state.json. Corrupt state mutes nothing, and says so: the reason
 * is surfaced as a `rejected` entry on the registry rather than swallowed.
 */
export function readSkillsState(stateText: string | null): SkillsState {
  if (!stateText || !stateText.trim()) return { disabled: [] }
  let state: { schema?: unknown; disabled?: unknown }
  try {
    state = JSON.parse(stateText) as { schema?: unknown; disabled?: unknown }
  } catch {
    return { disabled: [], error: 'unparseable — all skills treated as enabled' }
  }
  if (state === null || typeof state !== 'object' || Array.isArray(state)) {
    return { disabled: [], error: 'unparseable — all skills treated as enabled' }
  }
  if (state.schema !== 1 || !Array.isArray(state.disabled)) {
    return {
      disabled: [],
      error: 'expected {"schema": 1, "disabled": [...]} — all skills treated as enabled',
    }
  }
  return {
    disabled: [...new Set(state.disabled.filter(
      (name: unknown): name is string => typeof name === 'string' && SKILL_NAME.test(name)
    ))],
  }
}

/** Just the mute list. Kept for callers that do not care why state was ignored. */
export function parseDisabledSkills(stateText: string | null): string[] {
  return readSkillsState(stateText).disabled
}

/** Decode a single YAML scalar (bare, double-quoted, or single-quoted). */
function scalar(raw: string): string | null {
  const value = raw.trim()
  if (!value) return null
  if (value.startsWith('"')) {
    try {
      const parsed = JSON.parse(value)
      return typeof parsed === 'string' ? parsed : null
    } catch { return null }
  }
  if (value.startsWith("'")) {
    if (!value.endsWith("'")) return null
    return value.slice(1, -1).replace(/''/g, "'")
  }
  return value
}

/**
 * Frontmatter keys as they are actually written in the wild. Hyphens are the
 * common case in Claude-style packages (`allowed-tools:`, `license-key:`), so a
 * key regex without them rejects the whole package over a key nobody reads.
 */
const FRONTMATTER_KEY = /^([a-z0-9_-]+):\s*(.*)$/

/** YAML block-scalar indicators. `description: |` is multi-line by definition. */
const BLOCK_SCALAR = /^[|>][+-]?\d*$/

/**
 * Extract `name` and `description` from a SKILL.md YAML frontmatter block.
 *
 * Deliberately minimal in two directions:
 *
 * - **Tolerant about everything else.** Unrecognized keys (`adf`, `requires`,
 *   `allowed-tools`, ...), list items, and block continuations are SKIPPED, not
 *   rejected. This parser reads two fields out of a YAML document it does not
 *   otherwise understand; refusing a package because of a line it was never
 *   going to read would be a bug, not a validation.
 * - **Strict about the two it does read.** `name` must match the kebab rule and
 *   the directory; `description` must be a single-line scalar of at most 500
 *   characters with no control characters. A block scalar (`description: |`) is
 *   an error rather than the literal string "|".
 */
export function parseSkillFrontmatter(
  source: string
): { name: string; description: string } | { error: string } {
  const normalized = source.replace(/\r\n/g, '\n')
  const match = /^---\n([\s\S]*?)\n---(?:\n|$)/.exec(normalized)
  if (!match) return { error: 'missing YAML frontmatter' }
  const fields: Record<string, string> = {}
  for (const line of match[1].split('\n')) {
    if (!line.trim() || /^\s*#/.test(line)) continue
    if (/^\s/.test(line)) continue // nested content of a block such as requires:
    const item = FRONTMATTER_KEY.exec(line)
    // A top-level list item ("- foo"), a document separator, or anything else
    // this parser does not model: skip it and keep looking for the two keys.
    if (!item) continue
    if (!['name', 'description'].includes(item[1])) continue // ignore unrecognized keys
    if (fields[item[1]]) return { error: `duplicate ${item[1]}` }
    if (BLOCK_SCALAR.test(item[2].trim())) {
      return { error: `${item[1]} must be a single-line scalar` }
    }
    const value = scalar(item[2])
    if (value === null) return { error: `invalid ${item[1]}` }
    fields[item[1]] = value
  }
  if (!SKILL_NAME.test(fields.name ?? '')) return { error: 'invalid skill name' }
  if (!fields.description || fields.description.length > 500 || /[\r\n\0]/.test(fields.description)) {
    return { error: 'description must be one line and at most 500 characters' }
  }
  return { name: fields.name, description: fields.description }
}

/** Serialize a registry exactly as it is stored. */
export function serializeSkillRegistry(registry: SkillRegistry): string {
  return JSON.stringify(registry, null, 2) + '\n'
}

/**
 * Build the derived catalog from the installed manifests and the disable list.
 * Pure: no I/O, deterministic given the same inputs (sources are sorted by path).
 *
 * Every bound is enforced with a `rejected` entry rather than a silent drop, so
 * a package that never shows up in the catalog always has a stated reason.
 */
export function buildSkillRegistry(sources: SkillSource[], stateText: string | null): SkillIndexResult {
  const state = readSkillsState(stateText)
  const disabled = new Set(state.disabled)
  const skills: Record<string, SkillRegistryEntry> = {}
  const rejected: RejectedSkill[] = []

  // Fail-open, but never silently: an unreadable mute list means every skill
  // reads as enabled, which the agent must be able to see and fix.
  if (state.error) rejected.push({ path: SKILLS_STATE_PATH, reason: state.error })

  // Byte-wise, not localeCompare: cap eviction decides WHICH packages make the
  // catalog, so the order must not depend on the host's locale.
  const files = sources
    .filter(file => isSkillManifestPath(file.path))
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))

  for (const file of files) {
    const directory = file.path.slice(SKILLS_ROOT.length, -'/SKILL.md'.length)
    if (!SKILL_NAME.test(directory)) {
      rejected.push({ path: file.path, reason: `directory name must match ${SKILL_NAME.source}` })
      continue
    }
    if (file.size > MAX_SKILL_FILE_BYTES) {
      rejected.push({ path: file.path, reason: `exceeds ${MAX_SKILL_FILE_BYTES} bytes` })
      continue
    }
    const parsed = file.content === null
      ? { error: 'file disappeared while indexing' }
      : parseSkillFrontmatter(file.content)
    if ('error' in parsed) {
      rejected.push({ path: file.path, reason: parsed.error })
      continue
    }
    if (parsed.name !== directory) {
      rejected.push({ path: file.path, reason: 'frontmatter name must match directory' })
      continue
    }
    if (Object.keys(skills).length >= MAX_SKILLS) {
      rejected.push({ path: file.path, reason: `catalog is limited to ${MAX_SKILLS} skills` })
      continue
    }
    const enabled = !disabled.has(parsed.name)
    const candidate: SkillRegistryEntry = {
      name: parsed.name,
      // A muted skill keeps its entry so the agent can still see it exists and
      // unmute it, but costs a bare name rather than a description.
      ...(enabled ? { description: parsed.description } : {}),
      path: file.path,
      enabled
    }
    // The rejections found SO FAR count against the budget too — they ship in
    // the same file, so a skill must not be admitted on a size the file will
    // not actually have.
    const tentative = buildRegistryObject({ ...skills, [parsed.name]: candidate }, capRejected(rejected))
    if (Buffer.byteLength(serializeSkillRegistry(tentative), 'utf8') > MAX_REGISTRY_BYTES) {
      rejected.push({ path: file.path, reason: `catalog exceeds ${MAX_REGISTRY_BYTES} bytes` })
      continue
    }
    skills[parsed.name] = candidate
  }

  // Skills win the budget: with the admitted set fixed, drop rejection entries
  // from the tail until the file fits. Diagnostics must never evict a package
  // that would otherwise be advertised.
  let persisted = capRejected(rejected)
  let registry = buildRegistryObject(skills, persisted)
  let json = serializeSkillRegistry(registry)
  while (persisted.length && Buffer.byteLength(json, 'utf8') > MAX_REGISTRY_BYTES) {
    persisted = persisted.slice(0, -1)
    registry = buildRegistryObject(skills, persisted)
    json = serializeSkillRegistry(registry)
  }

  // `rejected` stays complete for callers (logs, the Studio panel, tests); only
  // the persisted copy is capped.
  return { registry, json, rejected, skillCount: Object.keys(skills).length }
}

/**
 * Bound the rejected list as it will be written: at most MAX_REGISTRY_REJECTED
 * entries with truncated fields, plus one line naming what was left out.
 */
function capRejected(rejected: RejectedSkill[]): RejectedSkill[] {
  const capped = rejected.slice(0, MAX_REGISTRY_REJECTED).map(entry => ({
    path: entry.path.slice(0, MAX_REJECTED_PATH_CHARS),
    reason: entry.reason.length > MAX_REJECTED_REASON_CHARS
      ? entry.reason.slice(0, MAX_REJECTED_REASON_CHARS - 1) + '…'
      : entry.reason,
  }))
  const omitted = rejected.length - capped.length
  if (omitted > 0) {
    capped.push({ path: SKILLS_ROOT, reason: `${omitted} further rejection(s) omitted` })
  }
  return capped
}

function buildRegistryObject(
  skills: Record<string, SkillRegistryEntry>,
  rejected: RejectedSkill[] = []
): SkillRegistry {
  return {
    schema: 1,
    $notes: SKILLS_REGISTRY_NOTES,
    skills,
    ...(rejected.length ? { rejected } : {}),
  }
}

// =============================================================================
// Workspace-backed indexer
// =============================================================================

/** The slice of AdfWorkspace the indexer needs. Kept structural for testability. */
export interface SkillIndexerHost {
  listFiles(): Array<{ path: string; size: number }>
  readFile(path: string): string | null
  writeFile(path: string, content: string, protection?: FileProtectionLevel): void
  getFileMeta(path: string): { protection: FileProtectionLevel } | null
  setFileProtection(path: string, protection: FileProtectionLevel): boolean
}

export interface SkillIndexerOptions {
  /** Read live — `skills.enabled` can be flipped mid-session by sys_update_config. */
  isEnabled: () => boolean
  /** Coalescing window for bursts of package writes (a multi-file install). */
  debounceMs?: number
  /**
   * Fired only when the catalog actually changed. The runtime turns this into a
   * keyed `loop_inject`; the injected system-prompt snapshot is NOT rewritten
   * mid-session (see prompt-file-injection.ts).
   */
  onRegistryChanged?: (json: string, result: SkillIndexResult) => void
  /** Best-effort diagnostics sink; never throws back into a write path. */
  onError?: (message: string) => void
}

export const DEFAULT_SKILL_INDEX_DEBOUNCE_MS = 250

export interface SkillIndexRunResult extends SkillIndexResult {
  changed: boolean
}

/**
 * Debounced reindexer bound to a workspace. `notifyPath` is called from the
 * workspace's single write/delete choke point, so EVERY writer — agent
 * `fs_write`, Studio `writeInternalFile`, daemon HTTP PUT, a lambda, the shell
 * — reindexes with no sync step and no per-caller wiring.
 */
export class SkillIndexer {
  private timer: NodeJS.Timeout | null = null
  private disposed = false

  constructor(
    private readonly host: SkillIndexerHost,
    private readonly options: SkillIndexerOptions
  ) {}

  /** Called for every workspace write/delete. Cheap no-op for unrelated paths. */
  notifyPath(path: string): void {
    if (this.disposed || !isSkillIndexPath(path)) return
    if (!this.isEnabled()) return
    this.schedule()
  }

  /** Run now, skipping the debounce (workspace open / session start). */
  refresh(): SkillIndexRunResult | null {
    if (this.disposed || !this.isEnabled()) return null
    this.cancel()
    return this.run()
  }

  /**
   * skills.enabled true→false: hand `skills-registry.json` back to the agent.
   *
   * The indexer holds the derived registry at `read_only` while it owns it.
   * Turning the subsystem off ends that ownership, and nothing else ever
   * downgrades a protection level — so without this the file is stranded:
   * generated, no longer maintained, and undeletable by the agent that now owns
   * the directory. Leave the file (it may still be useful); drop the lock.
   */
  releaseRegistry(): boolean {
    if (this.disposed) return false
    const meta = this.host.getFileMeta(SKILLS_REGISTRY_PATH)
    if (!meta || meta.protection === 'none') return false
    return withSource(SKILL_INDEX_SOURCE, () =>
      this.host.setFileProtection(SKILLS_REGISTRY_PATH, 'none'))
  }

  /** Flush a pending debounce immediately, if any. */
  flush(): void {
    if (!this.timer) return
    this.cancel()
    this.run()
  }

  dispose(): void {
    this.disposed = true
    this.cancel()
  }

  private isEnabled(): boolean {
    try {
      return this.options.isEnabled()
    } catch {
      return false
    }
  }

  private schedule(): void {
    if (this.timer) return
    this.timer = setTimeout(() => {
      this.timer = null
      if (this.disposed || !this.isEnabled()) return
      this.run()
    }, this.options.debounceMs ?? DEFAULT_SKILL_INDEX_DEBOUNCE_MS)
    this.timer.unref?.()
  }

  private cancel(): void {
    if (!this.timer) return
    clearTimeout(this.timer)
    this.timer = null
  }

  /** The registry write is the runtime's own action, never the agent write that
   *  happened to trigger it — a debounced timer would otherwise inherit the
   *  triggering call's async-local source and mislabel the provenance. */
  private run(): SkillIndexRunResult | null {
    return withSource(SKILL_INDEX_SOURCE, () => this.runIndex())
  }

  private runIndex(): SkillIndexRunResult | null {
    try {
      const sources: SkillSource[] = this.host.listFiles()
        .filter(file => isSkillManifestPath(file.path))
        .map(file => ({ path: file.path, size: file.size, content: this.host.readFile(file.path) }))
      const result = buildSkillRegistry(sources, this.host.readFile(SKILLS_STATE_PATH))

      const previous = this.host.readFile(SKILLS_REGISTRY_PATH)
      const changed = previous !== result.json
      // Runtime write: goes straight to the DB, bypassing the tool-layer
      // protection check that read_only imposes on the agent. That asymmetry is
      // the point — the file is the runtime's to own.
      if (changed) this.host.writeFile(SKILLS_REGISTRY_PATH, result.json, 'read_only')
      // Adoption: a registry an agent-space loader wrote already exists with
      // protection `none`. Take ownership on first index — subsequent loader
      // writes then bounce off the protection check as superseded.
      const meta = this.host.getFileMeta(SKILLS_REGISTRY_PATH)
      if (meta && meta.protection !== 'read_only') {
        this.host.setFileProtection(SKILLS_REGISTRY_PATH, 'read_only')
      }
      if (changed) {
        try { this.options.onRegistryChanged?.(result.json, result) }
        catch { /* notification is best-effort — never fail the index */ }
      }
      return { ...result, changed }
    } catch (err) {
      this.options.onError?.(`skill index failed: ${err instanceof Error ? err.message : String(err)}`)
      return null
    }
  }
}

// =============================================================================
// Config-flip fan-out
// =============================================================================

/** The workspace surface a skills config flip touches. Structural for testability. */
export interface SkillsConfigChangeTarget {
  refreshSkillIndex(): unknown
  releaseSkillRegistry(): boolean
}

/** Just enough of AgentConfig to see the flip. */
interface SkillsEnabledCarrier {
  skills?: { enabled?: boolean }
}

/**
 * Apply a `skills.enabled` change to the workspace. Call from EVERY config
 * write path — the sys_update_config fan-out, the Studio IPC handler, and the
 * daemon's HTTP config route — because the indexer is driven by file writes,
 * not by config, so nothing else notices the flip.
 *
 * - false→true reindexes SYNCHRONOUSLY. Without it the catalog stays empty (or,
 *   worse, an agent-authored `skills-registry.json` left at protection `none`
 *   stays un-adopted and gets injected as-is) until the next skill file write.
 * - true→false releases the registry's `read_only` hold (see releaseRegistry).
 *
 * A no-op when the flag did not change. Never throws: a config save must not
 * fail because indexing did.
 */
export function applySkillsConfigChange(
  workspace: SkillsConfigChangeTarget,
  previous: SkillsEnabledCarrier | null | undefined,
  next: SkillsEnabledCarrier | null | undefined
): void {
  const before = previous?.skills?.enabled === true
  const after = next?.skills?.enabled === true
  if (before === after) return
  try {
    if (after) workspace.refreshSkillIndex()
    else workspace.releaseSkillRegistry()
  } catch { /* diagnostics land in adf_logs via the indexer's onError */ }
}
