/**
 * Skill indexing — the runtime half of file-backed skills (spec §5.1).
 *
 * Two sources of truth, one derived file:
 *
 *   skills/<name>/SKILL.md   presence = installed; frontmatter = name/description
 *   skills-state.json        exception list { "schema": 1, "disabled": [...] }
 *          │
 *          ▼  this indexer (workspace write/delete choke point, debounced)
 *   skills-registry.json     derived, runtime-owned, protection read_only
 *
 * The validation, limits, and registry shape are ported from the agent-space
 * `skill-loader` lambda so agents that already ran the loader are adopted
 * as-is rather than re-indexed into a different catalog.
 *
 * Authority does not move with the mechanics: this file reads and writes
 * ordinary VFS rows. It never executes skill text, authorizes files, enables
 * tools, or relaxes HIL. `requires` is not read here at all.
 *
 * Headless-safe: no Electron, no SQLite, no runtime imports — the host is a
 * structural interface that AdfWorkspace satisfies, so the pure logic below is
 * directly unit-testable.
 */

import type { FileProtectionLevel } from '@shared/types/adf-v02.types'
import { withSource } from '../runtime/execution-context'

export const SKILLS_ROOT = 'skills/'
export const SKILLS_REGISTRY_PATH = 'skills-registry.json'
export const SKILLS_STATE_PATH = 'skills-state.json'

/** Ported verbatim from the skill-loader lambda — see skills/skill-loader/SKILL.md. */
export const MAX_SKILL_FILE_BYTES = 256 * 1024
export const MAX_SKILLS = 48
export const MAX_REGISTRY_BYTES = 32 * 1024

/** Execution-context source for everything the indexer writes. */
export const SKILL_INDEX_SOURCE = 'system:skill_indexer'

/** Category and coalescing key for the mid-session catalog `loop_inject`. */
export const SKILLS_REGISTRY_INJECT_KEY = 'skills_registry'

/** Prefix of the injected payload — states that it replaces earlier catalogs. */
export const SKILLS_REGISTRY_INJECT_PREFIX = 'This catalog supersedes previous skill catalogs:'

const SKILL_NAME = /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/
const SKILL_FILE_PATH = /^skills\/[^/]+\/SKILL\.md$/

/** Marks the registry as derived so a reader never mistakes it for a source file. */
export const SKILLS_REGISTRY_NOTES =
  'Generated by the ADF runtime — edit skills/ and skills-state.json instead'

export interface SkillRegistryEntry {
  name: string
  /** Omitted for disabled skills: a bare name is rediscoverable at ~zero token cost. */
  description?: string
  path: string
  enabled: boolean
}

export interface SkillRegistry {
  schema: 1
  $notes: string
  skills: Record<string, SkillRegistryEntry>
}

export interface RejectedSkill {
  path: string
  reason: string
}

/** One candidate `skills/<name>/SKILL.md` row as the indexer sees it. */
export interface SkillSource {
  path: string
  size: number
  /** null when the row disappeared between listing and reading. */
  content: string | null
}

export interface SkillIndexResult {
  registry: SkillRegistry
  /** Exactly the bytes written to `skills-registry.json` (pretty JSON + trailing newline). */
  json: string
  rejected: RejectedSkill[]
  skillCount: number
}

/** True for the paths whose writes/deletes must trigger a reindex. */
export function isSkillIndexPath(path: string): boolean {
  return path === SKILLS_STATE_PATH || SKILL_FILE_PATH.test(path)
}

/** True for a listed VFS row that is a skill package manifest. */
export function isSkillManifestPath(path: string): boolean {
  return SKILL_FILE_PATH.test(path)
}

/** Parse the `disabled` list out of skills-state.json. Corrupt state mutes nothing. */
export function parseDisabledSkills(stateText: string | null): string[] {
  if (!stateText) return []
  try {
    const state = JSON.parse(stateText) as { schema?: unknown; disabled?: unknown }
    if (state?.schema !== 1 || !Array.isArray(state.disabled)) return []
    return [...new Set(state.disabled.filter(
      (name: unknown): name is string => typeof name === 'string' && SKILL_NAME.test(name)
    ))]
  } catch {
    return []
  }
}

/** Decode a single YAML scalar (bare, double-quoted, or single-quoted). */
function scalar(raw: string): string | null {
  const value = raw.trim()
  if (!value) return null
  if (value.startsWith('"')) {
    try {
      const parsed = JSON.parse(value)
      return typeof parsed === 'string' ? parsed : null
    } catch { return null }
  }
  if (value.startsWith("'")) {
    if (!value.endsWith("'")) return null
    return value.slice(1, -1).replace(/''/g, "'")
  }
  return value
}

/**
 * Extract `name` and `description` from a SKILL.md YAML frontmatter block.
 * Deliberately minimal: unrecognized keys (`adf`, `requires`, ...) are ignored,
 * not rejected, so the convention can grow without invalidating catalogs.
 */
export function parseSkillFrontmatter(
  source: string
): { name: string; description: string } | { error: string } {
  const normalized = source.replace(/\r\n/g, '\n')
  const match = /^---\n([\s\S]*?)\n---(?:\n|$)/.exec(normalized)
  if (!match) return { error: 'missing YAML frontmatter' }
  const fields: Record<string, string> = {}
  for (const line of match[1].split('\n')) {
    if (!line.trim() || /^\s*#/.test(line)) continue
    if (/^\s/.test(line)) continue // nested content of an optional block such as requires:
    const item = /^([a-z_]+):\s*(.*)$/.exec(line)
    if (!item) return { error: `unsupported frontmatter line: ${line}` }
    if (!['name', 'description'].includes(item[1])) continue // ignore unrecognized keys
    if (fields[item[1]]) return { error: `duplicate ${item[1]}` }
    const value = scalar(item[2])
    if (value === null) return { error: `invalid ${item[1]}` }
    fields[item[1]] = value
  }
  if (!SKILL_NAME.test(fields.name ?? '')) return { error: 'invalid skill name' }
  if (!fields.description || fields.description.length > 500 || /[\r\n\0]/.test(fields.description)) {
    return { error: 'description must be one line and at most 500 characters' }
  }
  return { name: fields.name, description: fields.description }
}

/** Serialize a registry exactly as it is stored. */
export function serializeSkillRegistry(registry: SkillRegistry): string {
  return JSON.stringify(registry, null, 2) + '\n'
}

/**
 * Build the derived catalog from the installed manifests and the disable list.
 * Pure: no I/O, deterministic given the same inputs (sources are sorted by path).
 *
 * Every bound is enforced with a `rejected` entry rather than a silent drop, so
 * a package that never shows up in the catalog always has a stated reason.
 */
export function buildSkillRegistry(sources: SkillSource[], stateText: string | null): SkillIndexResult {
  const disabled = new Set(parseDisabledSkills(stateText))
  const skills: Record<string, SkillRegistryEntry> = {}
  const rejected: RejectedSkill[] = []

  const files = sources
    .filter(file => isSkillManifestPath(file.path))
    .sort((a, b) => a.path.localeCompare(b.path))

  for (const file of files) {
    const directory = file.path.slice(SKILLS_ROOT.length, -'/SKILL.md'.length)
    if (!SKILL_NAME.test(directory)) continue
    if (file.size > MAX_SKILL_FILE_BYTES) {
      rejected.push({ path: file.path, reason: `exceeds ${MAX_SKILL_FILE_BYTES} bytes` })
      continue
    }
    const parsed = file.content === null
      ? { error: 'file disappeared while indexing' }
      : parseSkillFrontmatter(file.content)
    if ('error' in parsed) {
      rejected.push({ path: file.path, reason: parsed.error })
      continue
    }
    if (parsed.name !== directory) {
      rejected.push({ path: file.path, reason: 'frontmatter name must match directory' })
      continue
    }
    if (Object.keys(skills).length >= MAX_SKILLS) {
      rejected.push({ path: file.path, reason: `catalog is limited to ${MAX_SKILLS} skills` })
      continue
    }
    const enabled = !disabled.has(parsed.name)
    const candidate: SkillRegistryEntry = {
      name: parsed.name,
      // A muted skill keeps its entry so the agent can still see it exists and
      // unmute it, but costs a bare name rather than a description.
      ...(enabled ? { description: parsed.description } : {}),
      path: file.path,
      enabled
    }
    const tentative = buildRegistryObject({ ...skills, [parsed.name]: candidate })
    if (Buffer.byteLength(serializeSkillRegistry(tentative), 'utf8') > MAX_REGISTRY_BYTES) {
      rejected.push({ path: file.path, reason: `catalog exceeds ${MAX_REGISTRY_BYTES} bytes` })
      continue
    }
    skills[parsed.name] = candidate
  }

  const registry = buildRegistryObject(skills)
  return { registry, json: serializeSkillRegistry(registry), rejected, skillCount: Object.keys(skills).length }
}

function buildRegistryObject(skills: Record<string, SkillRegistryEntry>): SkillRegistry {
  return { schema: 1, $notes: SKILLS_REGISTRY_NOTES, skills }
}

// =============================================================================
// Workspace-backed indexer
// =============================================================================

/** The slice of AdfWorkspace the indexer needs. Kept structural for testability. */
export interface SkillIndexerHost {
  listFiles(): Array<{ path: string; size: number }>
  readFile(path: string): string | null
  writeFile(path: string, content: string, protection?: FileProtectionLevel): void
  getFileMeta(path: string): { protection: FileProtectionLevel } | null
  setFileProtection(path: string, protection: FileProtectionLevel): boolean
}

export interface SkillIndexerOptions {
  /** Read live — `skills.enabled` can be flipped mid-session by sys_update_config. */
  isEnabled: () => boolean
  /** Coalescing window for bursts of package writes (a multi-file install). */
  debounceMs?: number
  /**
   * Fired only when the catalog actually changed. The runtime turns this into a
   * keyed `loop_inject`; the injected system-prompt snapshot is NOT rewritten
   * mid-session (see prompt-file-injection.ts).
   */
  onRegistryChanged?: (json: string, result: SkillIndexResult) => void
  /** Best-effort diagnostics sink; never throws back into a write path. */
  onError?: (message: string) => void
}

export const DEFAULT_SKILL_INDEX_DEBOUNCE_MS = 250

export interface SkillIndexRunResult extends SkillIndexResult {
  changed: boolean
}

/**
 * Debounced reindexer bound to a workspace. `notifyPath` is called from the
 * workspace's single write/delete choke point, so EVERY writer — agent
 * `fs_write`, Studio `writeInternalFile`, daemon HTTP PUT, a lambda, the shell
 * — reindexes with no sync step and no per-caller wiring.
 */
export class SkillIndexer {
  private timer: NodeJS.Timeout | null = null
  private disposed = false

  constructor(
    private readonly host: SkillIndexerHost,
    private readonly options: SkillIndexerOptions
  ) {}

  /** Called for every workspace write/delete. Cheap no-op for unrelated paths. */
  notifyPath(path: string): void {
    if (this.disposed || !isSkillIndexPath(path)) return
    if (!this.isEnabled()) return
    this.schedule()
  }

  /** Run now, skipping the debounce (workspace open / session start). */
  refresh(): SkillIndexRunResult | null {
    if (this.disposed || !this.isEnabled()) return null
    this.cancel()
    return this.run()
  }

  /** Flush a pending debounce immediately, if any. */
  flush(): void {
    if (!this.timer) return
    this.cancel()
    this.run()
  }

  dispose(): void {
    this.disposed = true
    this.cancel()
  }

  private isEnabled(): boolean {
    try {
      return this.options.isEnabled()
    } catch {
      return false
    }
  }

  private schedule(): void {
    if (this.timer) return
    this.timer = setTimeout(() => {
      this.timer = null
      if (this.disposed || !this.isEnabled()) return
      this.run()
    }, this.options.debounceMs ?? DEFAULT_SKILL_INDEX_DEBOUNCE_MS)
    this.timer.unref?.()
  }

  private cancel(): void {
    if (!this.timer) return
    clearTimeout(this.timer)
    this.timer = null
  }

  /** The registry write is the runtime's own action, never the agent write that
   *  happened to trigger it — a debounced timer would otherwise inherit the
   *  triggering call's async-local source and mislabel the provenance. */
  private run(): SkillIndexRunResult | null {
    return withSource(SKILL_INDEX_SOURCE, () => this.runIndex())
  }

  private runIndex(): SkillIndexRunResult | null {
    try {
      const sources: SkillSource[] = this.host.listFiles()
        .filter(file => isSkillManifestPath(file.path))
        .map(file => ({ path: file.path, size: file.size, content: this.host.readFile(file.path) }))
      const result = buildSkillRegistry(sources, this.host.readFile(SKILLS_STATE_PATH))

      const previous = this.host.readFile(SKILLS_REGISTRY_PATH)
      const changed = previous !== result.json
      // Runtime write: goes straight to the DB, bypassing the tool-layer
      // protection check that read_only imposes on the agent. That asymmetry is
      // the point — the file is the runtime's to own.
      if (changed) this.host.writeFile(SKILLS_REGISTRY_PATH, result.json, 'read_only')
      // Adoption: a registry an agent-space loader wrote already exists with
      // protection `none`. Take ownership on first index — subsequent loader
      // writes then bounce off the protection check as superseded.
      const meta = this.host.getFileMeta(SKILLS_REGISTRY_PATH)
      if (meta && meta.protection !== 'read_only') {
        this.host.setFileProtection(SKILLS_REGISTRY_PATH, 'read_only')
      }
      if (changed) {
        try { this.options.onRegistryChanged?.(result.json, result) }
        catch { /* notification is best-effort — never fail the index */ }
      }
      return { ...result, changed }
    } catch (err) {
      this.options.onError?.(`skill index failed: ${err instanceof Error ? err.message : String(err)}`)
      return null
    }
  }
}
