import { describe, expect, it, vi } from 'vitest'
import {
  MAX_REGISTRY_BYTES,
  MAX_SKILLS,
  MAX_SKILL_FILE_BYTES,
  SKILLS_REGISTRY_PATH,
  SkillIndexer,
  buildSkillRegistry,
  isSkillIndexPath,
  parseDisabledSkills,
  parseSkillFrontmatter,
  type SkillIndexerHost,
  type SkillSource,
} from '../../src/main/adf/skill-indexer'
import type { FileProtectionLevel } from '../../src/shared/types/adf-v02.types'

function manifest(name: string, description = `The ${name} skill.`, extra = ''): SkillSource {
  const content = `---\nname: ${name}\ndescription: ${description}\n${extra}---\n\n# ${name}\n`
  return { path: `skills/${name}/SKILL.md`, size: Buffer.byteLength(content), content }
}

/** In-memory stand-in for the AdfWorkspace slice the indexer uses. */
function createHost(files: Map<string, string>, protections = new Map<string, FileProtectionLevel>()): SkillIndexerHost & {
  files: Map<string, string>
  protections: Map<string, FileProtectionLevel>
} {
  return {
    files,
    protections,
    listFiles: () => [...files].map(([path, content]) => ({ path, size: Buffer.byteLength(content) })),
    readFile: (path) => files.get(path) ?? null,
    writeFile: (path, content, protection) => {
      const isNew = !files.has(path)
      files.set(path, content)
      if (isNew) protections.set(path, protection ?? 'none')
    },
    getFileMeta: (path) => (files.has(path) ? { protection: protections.get(path) ?? 'none' } : null),
    setFileProtection: (path, protection) => {
      if (!files.has(path)) return false
      protections.set(path, protection)
      return true
    },
  }
}

describe('skill frontmatter parsing', () => {
  it('accepts the required pair and ignores unrecognized keys', () => {
    const source = '---\nname: alpha\ndescription: Does alpha things.\nadf: ">=0.2"\nrequires:\n  tools: [fs_read]\n---\n'
    expect(parseSkillFrontmatter(source)).toEqual({ name: 'alpha', description: 'Does alpha things.' })
  })

  it('decodes quoted scalars', () => {
    expect(parseSkillFrontmatter('---\nname: "alpha"\ndescription: \'It\'\'s fine.\'\n---\n'))
      .toEqual({ name: 'alpha', description: "It's fine." })
  })

  it('rejects missing frontmatter, bad names, and oversized descriptions', () => {
    expect(parseSkillFrontmatter('no frontmatter')).toEqual({ error: 'missing YAML frontmatter' })
    expect(parseSkillFrontmatter('---\nname: Alpha\ndescription: x\n---\n')).toEqual({ error: 'invalid skill name' })
    expect(parseSkillFrontmatter('---\nname: alpha\n---\n'))
      .toEqual({ error: 'description must be one line and at most 500 characters' })
    expect(parseSkillFrontmatter(`---\nname: alpha\ndescription: ${'x'.repeat(501)}\n---\n`))
      .toEqual({ error: 'description must be one line and at most 500 characters' })
    expect(parseSkillFrontmatter('---\nname: alpha\nname: beta\ndescription: x\n---\n'))
      .toEqual({ error: 'duplicate name' })
  })

  it('normalizes CRLF so a Windows-authored package still parses', () => {
    expect(parseSkillFrontmatter('---\r\nname: alpha\r\ndescription: Windows.\r\n---\r\n'))
      .toEqual({ name: 'alpha', description: 'Windows.' })
  })
})

describe('skills-state.json parsing', () => {
  it('reads a well-formed disable list and de-duplicates it', () => {
    expect(parseDisabledSkills('{"schema":1,"disabled":["a","a","b"]}')).toEqual(['a', 'b'])
  })

  it('mutes nothing on absent, corrupt, wrong-schema, or invalid-name state', () => {
    expect(parseDisabledSkills(null)).toEqual([])
    expect(parseDisabledSkills('{oops')).toEqual([])
    expect(parseDisabledSkills('{"schema":2,"disabled":["a"]}')).toEqual([])
    expect(parseDisabledSkills('{"schema":1,"disabled":"a"}')).toEqual([])
    expect(parseDisabledSkills('{"schema":1,"disabled":["Bad Name",7,"ok"]}')).toEqual(['ok'])
  })
})

describe('registry construction', () => {
  it('emits the schema-1 shape with a generated-file note', () => {
    const { registry, json, rejected, skillCount } = buildSkillRegistry([manifest('alpha')], null)
    expect(rejected).toEqual([])
    expect(skillCount).toBe(1)
    expect(registry.schema).toBe(1)
    expect(registry.$notes).toContain('Generated by the ADF runtime')
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      description: 'The alpha skill.',
      path: 'skills/alpha/SKILL.md',
      enabled: true,
    })
    expect(json.endsWith('\n')).toBe(true)
    expect(JSON.parse(json)).toEqual(registry)
  })

  it('is deterministic regardless of listing order', () => {
    const a = buildSkillRegistry([manifest('alpha'), manifest('beta')], null)
    const b = buildSkillRegistry([manifest('beta'), manifest('alpha')], null)
    expect(a.json).toBe(b.json)
  })

  it('keeps a disabled skill as a bare name with no description', () => {
    const { registry } = buildSkillRegistry([manifest('alpha')], '{"schema":1,"disabled":["alpha"]}')
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      path: 'skills/alpha/SKILL.md',
      enabled: false,
    })
    expect('description' in registry.skills.alpha).toBe(false)
  })

  it('ignores rows that are not skill manifests', () => {
    const { skillCount } = buildSkillRegistry([
      manifest('alpha'),
      { path: 'skills/alpha/references/notes.md', size: 4, content: 'note' },
      { path: 'skills/SKILL.md', size: 4, content: 'note' },
      { path: 'skills/alpha/nested/SKILL.md', size: 4, content: 'note' },
      { path: 'README.md', size: 4, content: 'note' },
    ], null)
    expect(skillCount).toBe(1)
  })

  it('rejects a manifest whose name disagrees with its directory', () => {
    const source = manifest('alpha')
    source.path = 'skills/beta/SKILL.md'
    const { rejected, skillCount } = buildSkillRegistry([source], null)
    expect(skillCount).toBe(0)
    expect(rejected).toEqual([{ path: 'skills/beta/SKILL.md', reason: 'frontmatter name must match directory' }])
  })

  it('rejects a manifest that disappeared between listing and reading', () => {
    const { rejected } = buildSkillRegistry([{ path: 'skills/alpha/SKILL.md', size: 10, content: null }], null)
    expect(rejected).toEqual([{ path: 'skills/alpha/SKILL.md', reason: 'file disappeared while indexing' }])
  })

  it('rejects an oversized manifest without reading it', () => {
    const source = { ...manifest('alpha'), size: MAX_SKILL_FILE_BYTES + 1 }
    const { rejected, skillCount } = buildSkillRegistry([source], null)
    expect(skillCount).toBe(0)
    expect(rejected).toEqual([{ path: 'skills/alpha/SKILL.md', reason: `exceeds ${MAX_SKILL_FILE_BYTES} bytes` }])
  })

  it('caps the catalog at MAX_SKILLS and reports the overflow', () => {
    const sources = Array.from({ length: MAX_SKILLS + 2 }, (_, i) => manifest(`skill-${String(i).padStart(3, '0')}`))
    const { skillCount, rejected } = buildSkillRegistry(sources, null)
    expect(skillCount).toBe(MAX_SKILLS)
    expect(rejected).toHaveLength(2)
    expect(rejected[0].reason).toBe(`catalog is limited to ${MAX_SKILLS} skills`)
  })

  it('caps the serialized registry size and reports the overflow', () => {
    // Worst case that still fits under MAX_SKILLS: 63-char names and
    // 500-char descriptions overflow the 32 KB registry before the 48th entry.
    const long = 'x'.repeat(500)
    const sources = Array.from({ length: MAX_SKILLS }, (_, i) => {
      const prefix = `skill-${String(i).padStart(3, '0')}-`
      return manifest(prefix + 'x'.repeat(63 - prefix.length), long)
    })
    const { rejected, json } = buildSkillRegistry(sources, null)
    expect(Buffer.byteLength(json, 'utf8')).toBeLessThanOrEqual(MAX_REGISTRY_BYTES)
    expect(rejected.length).toBeGreaterThan(0)
    expect(rejected[rejected.length - 1].reason).toBe(`catalog exceeds ${MAX_REGISTRY_BYTES} bytes`)
  })
})

describe('watched paths', () => {
  it('matches manifests and the state file only', () => {
    expect(isSkillIndexPath('skills/alpha/SKILL.md')).toBe(true)
    expect(isSkillIndexPath('skills-state.json')).toBe(true)
    expect(isSkillIndexPath(SKILLS_REGISTRY_PATH)).toBe(false)
    expect(isSkillIndexPath('skills/alpha/scripts/run.ts')).toBe(false)
    expect(isSkillIndexPath('lib/skill-indexer.ts')).toBe(false)
  })
})

describe('SkillIndexer', () => {
  it('writes the registry read_only and reports the change once', () => {
    const files = new Map([[manifest('alpha').path, manifest('alpha').content!]])
    const host = createHost(files)
    const onRegistryChanged = vi.fn()
    const indexer = new SkillIndexer(host, { isEnabled: () => true, onRegistryChanged })

    const first = indexer.refresh()
    expect(first?.changed).toBe(true)
    expect(host.protections.get(SKILLS_REGISTRY_PATH)).toBe('read_only')
    expect(onRegistryChanged).toHaveBeenCalledTimes(1)
    expect(JSON.parse(files.get(SKILLS_REGISTRY_PATH)!).skills.alpha.enabled).toBe(true)

    const second = indexer.refresh()
    expect(second?.changed).toBe(false)
    expect(onRegistryChanged).toHaveBeenCalledTimes(1)
    indexer.dispose()
  })

  it('adopts an agent-authored registry by flipping it to read_only', () => {
    const files = new Map([
      [manifest('alpha').path, manifest('alpha').content!],
      [SKILLS_REGISTRY_PATH, '{"schema":1,"skills":{}}'],
    ])
    const host = createHost(files, new Map<string, FileProtectionLevel>([[SKILLS_REGISTRY_PATH, 'none']]))
    new SkillIndexer(host, { isEnabled: () => true }).refresh()
    expect(host.protections.get(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })

  it('does nothing at all when skills.enabled is false', () => {
    const files = new Map([[manifest('alpha').path, manifest('alpha').content!]])
    const host = createHost(files)
    const indexer = new SkillIndexer(host, { isEnabled: () => false })
    expect(indexer.refresh()).toBeNull()
    indexer.notifyPath('skills/alpha/SKILL.md')
    indexer.flush()
    expect(files.has(SKILLS_REGISTRY_PATH)).toBe(false)
  })

  it('coalesces a burst of writes into a single index', () => {
    const files = new Map([[manifest('alpha').path, manifest('alpha').content!]])
    const host = createHost(files)
    const listFiles = vi.spyOn(host, 'listFiles')
    const indexer = new SkillIndexer(host, { isEnabled: () => true })

    indexer.notifyPath('skills/alpha/SKILL.md')
    indexer.notifyPath('skills/beta/SKILL.md')
    indexer.notifyPath('skills-state.json')
    indexer.notifyPath('README.md')
    indexer.flush()

    expect(listFiles).toHaveBeenCalledTimes(1)
    indexer.dispose()
  })

  it('never lets an index failure escape into the write path', () => {
    const host = createHost(new Map())
    host.listFiles = () => { throw new Error('db closed') }
    const onError = vi.fn()
    expect(new SkillIndexer(host, { isEnabled: () => true, onError }).refresh()).toBeNull()
    expect(onError).toHaveBeenCalledWith(expect.stringContaining('db closed'))
  })
})
