import { describe, it, expect, afterEach } from 'vitest'
import { mkdtempSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { AdfWorkspace } from '../../src/main/adf/adf-workspace'
import { SKILLS_REGISTRY_PATH, SKILLS_STATE_PATH } from '../../src/main/adf/skill-indexer'

const MANIFEST = '---\nname: alpha\ndescription: Does alpha things.\n---\n\n# Alpha\n'

/** The indexer debounces ~250 ms; give it comfortable headroom. */
const settle = () => new Promise(resolve => setTimeout(resolve, 500))

describe('skill indexing at the workspace write choke point', () => {
  const dirs: string[] = []
  const open: AdfWorkspace[] = []

  afterEach(() => {
    for (const workspace of open.splice(0)) {
      try { workspace.close() } catch { /* already closed */ }
    }
    for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
  })

  function newWorkspace(skillsEnabled: boolean): AdfWorkspace {
    const dir = mkdtempSync(join(tmpdir(), 'adf-skill-index-'))
    dirs.push(dir)
    const workspace = AdfWorkspace.create(join(dir, 'agent.adf'), { name: 'indexed' })
    open.push(workspace)
    const config = workspace.getAgentConfig()
    workspace.setAgentConfig({ ...config, skills: { enabled: skillsEnabled } })
    return workspace
  }

  it('indexes an ordinary fs_write and owns the generated registry', async () => {
    const workspace = newWorkspace(true)
    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()

    const registry = JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry.schema).toBe(1)
    expect(registry.$notes).toContain('Generated by the ADF runtime')
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      description: 'Does alpha things.',
      path: 'skills/alpha/SKILL.md',
      enabled: true,
    })
    // read_only is what makes the agent's own fs_write to the registry bounce.
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })

  it('reindexes when the mute list changes and reports it to the live session', async () => {
    const workspace = newWorkspace(true)
    const catalogs: string[] = []
    workspace.setOnSkillRegistryChangedCallback((json) => { catalogs.push(json) })

    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(catalogs).toHaveLength(1)

    workspace.writeFile(SKILLS_STATE_PATH, '{"schema":1,"disabled":["alpha"]}')
    await settle()
    expect(catalogs).toHaveLength(2)

    const registry = JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      path: 'skills/alpha/SKILL.md',
      enabled: false,
    })

    // An unrelated write neither reindexes nor re-notifies.
    workspace.writeFile('notes.md', 'hello')
    await settle()
    expect(catalogs).toHaveLength(2)
  })

  it('drops a skill from the catalog when its package is deleted', async () => {
    const workspace = newWorkspace(true)
    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(workspace.deleteFile('skills/alpha/SKILL.md')).toBe(true)
    await settle()
    expect(JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!).skills).toEqual({})
  })

  it('adopts a pre-existing agent-authored registry by taking protection', async () => {
    const workspace = newWorkspace(true)
    workspace.writeFile(SKILLS_REGISTRY_PATH, '{"schema":1,"skills":{}}')
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('none')

    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })

  it('writes nothing while skills.enabled is false, and picks up on the next write once on', async () => {
    const workspace = newWorkspace(false)
    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(workspace.readFile(SKILLS_REGISTRY_PATH)).toBeNull()
    expect(workspace.refreshSkillIndex()).toBeNull()

    // The enabled check is read live, not captured at construction.
    workspace.setAgentConfig({ ...workspace.getAgentConfig(), skills: { enabled: true } })
    expect(workspace.refreshSkillIndex()?.skillCount).toBe(1)
    expect(workspace.readFile(SKILLS_REGISTRY_PATH)).not.toBeNull()
  })
})
