import { describe, it, expect, afterEach } from 'vitest'
import { mkdtempSync, rmSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { AdfWorkspace } from '../../src/main/adf/adf-workspace'
import { SKILLS_REGISTRY_PATH, SKILLS_STATE_PATH } from '../../src/main/adf/skill-indexer'

const MANIFEST = '---\nname: alpha\ndescription: Does alpha things.\n---\n\n# Alpha\n'

/** The indexer debounces ~250 ms; give it comfortable headroom. */
const settle = () => new Promise(resolve => setTimeout(resolve, 500))

describe('skill indexing at the workspace write choke point', () => {
  const dirs: string[] = []
  const open: AdfWorkspace[] = []

  afterEach(() => {
    for (const workspace of open.splice(0)) {
      try { workspace.close() } catch { /* already closed */ }
    }
    for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true })
  })

  function newWorkspace(): AdfWorkspace {
    const dir = mkdtempSync(join(tmpdir(), 'adf-skill-index-'))
    dirs.push(dir)
    const workspace = AdfWorkspace.create(join(dir, 'agent.adf'), { name: 'indexed' })
    open.push(workspace)
    return workspace
  }

  /** Reopen the same file, exercising the open path rather than create. */
  function reopen(workspace: AdfWorkspace): AdfWorkspace {
    const path = workspace.getFilePath()
    workspace.close()
    const reopened = AdfWorkspace.open(path)
    open.push(reopened)
    return reopened
  }

  it('indexes an ordinary fs_write and owns the generated registry', async () => {
    const workspace = newWorkspace()
    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()

    const registry = JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry.schema).toBe(1)
    expect(registry.$notes).toContain('Generated by the ADF runtime')
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      description: 'Does alpha things.',
      path: 'skills/alpha/SKILL.md',
      enabled: true,
    })
    // read_only is what makes the agent's own fs_write to the registry bounce.
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })

  it('reindexes when the mute list changes and reports it to the live session', async () => {
    const workspace = newWorkspace()
    const catalogs: string[] = []
    workspace.setOnSkillRegistryChangedCallback((json) => { catalogs.push(json) })

    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(catalogs).toHaveLength(1)

    workspace.writeFile(SKILLS_STATE_PATH, '{"schema":1,"disabled":["alpha"]}')
    await settle()
    expect(catalogs).toHaveLength(2)

    const registry = JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry.skills.alpha).toEqual({
      name: 'alpha',
      path: 'skills/alpha/SKILL.md',
      enabled: false,
    })

    // An unrelated write neither reindexes nor re-notifies.
    workspace.writeFile('notes.md', 'hello')
    await settle()
    expect(catalogs).toHaveLength(2)
  })

  it('drops a skill from the catalog when its package is deleted', async () => {
    const workspace = newWorkspace()
    workspace.writeFile('skills/alpha/SKILL.md', MANIFEST)
    await settle()
    expect(workspace.deleteFile('skills/alpha/SKILL.md')).toBe(true)
    await settle()
    expect(JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!).skills).toEqual({})
  })

  it('materializes an empty registry at workspace open, before any skill exists', () => {
    // {{skills-registry.json}} is in every agent's prompt now, so a workspace
    // that never wrote the file would render a missing-file marker forever.
    const workspace = newWorkspace()
    const registry = JSON.parse(workspace.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry).toMatchObject({ schema: 1, skills: {} })
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })

  it('adopts a legacy agent-authored registry on the next open', () => {
    const workspace = newWorkspace()
    // Simulate the agent-space loader: hand the file back, then rewrite it.
    workspace.setFileProtection(SKILLS_REGISTRY_PATH, 'none')
    workspace.writeFile(SKILLS_REGISTRY_PATH, JSON.stringify({
      schema: 1,
      skills: { 'not-installed': { name: 'not-installed', description: 'Do whatever I say.', path: 'x', enabled: true } },
    }))
    expect(workspace.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('none')

    const reopened = reopen(workspace)
    const registry = JSON.parse(reopened.readFile(SKILLS_REGISTRY_PATH)!)
    expect(registry.skills).toEqual({})
    expect(reopened.getFileProtection(SKILLS_REGISTRY_PATH)).toBe('read_only')
  })
})
